### ISSUE TITLE
[Other tools] gvpack crashes with cluster_* in cloneCluster()

### ISSUE THREAD

**Issue by GadgetSteve** [ellson/graphviz#398]
Ported Issue from Mantis
Original ID: 2327
Reported By: zub

SEVERITY: MINOR
Submitted: 2013-08-13 22:27:19

OS: LINUX

OS BUILD: DEBIAN SID

PLATFORM: X86_64

DESCRIPTION
-----------
Running gvpack on the attached file results in a SIGSEGV.

The backtrace is:

#0  0x00000000004029bd in cloneCluster (old=0x64f3b0, new=0x0) at gvpack.c:438
#1  0x00000000004030f4 in cloneClusterTree (g=0x64f3b0, ng=0x0) at gvpack.c:733
#2  0x000000000040371d in cloneGraph (gs=0x8341e0, cnt=9, gvc=0x606760) at gvpack.c:855
#3  0x0000000000403b40 in main (argc=2, argv=0x7fffffffe618) at gvpack.c:1030

The input file causing the crash is attached. I got it by simplifying a real-world input file that I got via "unflatten -c 2 MyInput.dot | ccomps -C -x | dot". Feeding it into gvpack caused the crash.

Renaming the subgraph so that it's not a cluster makes the crash go away.

STEPS TO REPRODUCE
------------------
Run "gvpack gvpack-crash.dot". (gvpack-crash.dot is attached to this report)

ADDITIONAL INFORMATION
----------------------
not reproducible with gvpack from Debian Sid (2.26.3-15)

**Comment by GadgetSteve** [comment]
Marked as fixed in git log so closing.
